#!/usr/bin/env python2.5

import pygtk
pygtk.require('2.0')
import gtk

#import osso
#osso_c = osso.Context("djmote", "0.1.0", False)

import djmote.ui

dui = djmote.ui.DjmoteUI()
dui.build()
dui.run()


# vim: ts=4 sw=4 expandtab
