#!/usr/bin/env python2.5

import pygtk
pygtk.require('2.0')
import gtk
import djmote.ui


if __name__ == '__main__':
    dui = djmote.ui.DjmoteUI()
    dui.build()
    dui.run()

# vim: ts=4 sw=4 expandtab
