#!/usr/bin/env python2.4
# Python with version is required here to prevent the Maemo platform from using
# the older Python 2.3.
# Python 2.4 is chosen here because it is what is available for the Nokia 770.

import pygtk
pygtk.require('2.0')
import gtk

import djmote.ui

dui = djmote.ui.DjmoteUI()
dui.build()
dui.run()


# vim: ts=4 sw=4 expandtab
