#!/usr/bin/env python
"""
This is a deejayd test server executable
"""

import sys, os

print sys.path

from deejayd.net.deejaydProtocol import DeejaydFactory
from deejayd.mediadb.database import sqliteDatabase
from deejayd.mediadb.deejaydDB import DeejaydDB
from twisted.internet import reactor
from twisted.python import log

# argv[1] should be port
# argv[2] should be music dir
# argv[3] should be db filename
if len(sys.argv) != 4:
    sys.exit('Incorrect invocation')

port = sys.argv[1]
musicDir = sys.argv[2]
dbfilename = sys.argv[3]

log.startLogging(open('/tmp/testdeejayd.log', 'w'))

db = sqliteDatabase(dbfilename)

ddb = DeejaydDB(db, musicDir)

factory = DeejaydFactory(ddb)
reactor.listenTCP(int(port), factory)

ddb.startUpdate()

def printReady():
    os.write(2, 'ready\n')

reactor.addSystemEventTrigger('after', 'startup', printReady)

reactor.run()

# vim: ts=4 sw=4 expandtab
