#!/usr/bin/env python
"""
This is a deejayd test server executable
"""

import sys, os

print sys.path

from deejayd.net.deejaydProtocol import DeejaydFactory
from deejayd.database.sqlite import SqliteDatabase
from deejayd.mediadb.library import AudioLibrary,VideoLibrary
from deejayd.ui.config import DeejaydConfig
from twisted.internet import reactor
from twisted.python import log
from deejayd.player import gstreamer

# argv[1] should be port
# argv[2] should be music dir
# argv[3] should be db filename
if len(sys.argv) != 4:
    sys.exit('Incorrect invocation')

port = sys.argv[1]
music_dir = sys.argv[2]
dbfilename = sys.argv[3]

log.startLogging(open('/tmp/testdeejayd.log', 'w'))

config = DeejaydConfig()

db = SqliteDatabase(dbfilename)
db.connect()

player = gstreamer.GstreamerPlayer(db,config)

audio_library = AudioLibrary(db, player, music_dir)

factory = DeejaydFactory(db,player,audio_library)
reactor.listenTCP(int(port), factory)

audio_library._update()

def printReady():
    os.write(2, 'ready\n')

reactor.addSystemEventTrigger('after', 'startup', printReady)

reactor.run()

# vim: ts=4 sw=4 expandtab
